export default {
  ADD_CATEGORIES: "ADD_CATEGORIES",
  REMOVE_CATEGORIES: "REMOVE_CATEGORIES",
  EDIT_CATEGORIES: "EDIT_CATEGORIES",
  ADD_PRODUCTS: "ADD_PRODUCTS",
  REMOVE_PRODUCTS: "REMOVE_PRODUCTS",
  EDIT_PRODUCTS: "EDIT_PRODUCTS",
};
